const HELP = {
  'FRONT': {title: `Warhammer 40,000 Crusade Tracker`, content: `Each page has a help message like this one that can be minimised. \n This page shows all Crusade Forces you have created. You can click "Add New Force" to create a new one. \n The Battle Setup button takes you to the Battle Setup allowing you to track any battles that your Forces have fought. \n The Battle History button takes you to a log of Battles fought.`},
  'MAIN': {title: `Crusade Force`, content: `Enter your Crusade Force details here. Changes to Crusade Forces are saved automatically. All information is saved in your browser local storage (meaning you can refresh the page and it will remain) \n Use the Requisition Log to enter requisitions that your Crusade Force has used. Currently this is done manually because of the large number of requisitions that exist in the rules and various codices. \n Your Crusade Units will appear as cards with some details and they can be expanded to show more.`},
  'ADD': {title: `Add a Unit`, content: `Enter the details of a unit here. \n This page allows for pre-existing units to be added to a Force (i.e., if you are converting a Force tracked elsewhere) however any battles they have fought will not be tracked. \n The Unit Name, Type, Role, and Power Rating are required fields. \n Rank is automatically adjusted based on Experience Points and will be updated after battles.`},
  'BATTLESETUP': {title: `Battle Setup`, content: `This page contains the setup for a battle. If both player's Crusade Forces are tracked using this site, you can use the toggle to include them both in the battle. \n Mission rewards that grant additional Requisition are added automatically, and rewards that grant free uses of Increase Supply Limit can be claimed on the Crusade Force page. All others need to be manually added. \n When you select your Crusade Force a list of units will appear in the Army Roster section. Check the box next to the unit to add it to the battle. Updating their Crusade Cards happens on the next page.`},
  'BATTLERES': {title: `Battle Resolution`, content: `All units listed below will gain 1XP for participating in the battle. The XP gain from destroying enemies will be also be calculated based on the number entered. \n Enter any additional XP gains from Agendas or other bonuses in the XP field. If a unit is destroyed during the battle check that checkbox, and if they recieve a Devastating Blow as a result, enter the XP loss in this field. \n If a unit is Marked for Greatness check the box and the bonus XP will be added. \n Currently each unit must be individually saved before clicking Finalise Battle` },
  'EDIT': {title: `Edit a Unit`, content: `You can edit an existing unit. Adding Relics, Traits, or Specialist Reinforcements to an existing unit will not cost Requisition Points. These must be added in the Requisition Log.`},
  'BATTLEHISTORY': {title: `Battle History`, content: `Below is a list of Battles fought`}
}

export default HELP